CREATE DATABASE fms;

USE fms;

CREATE TABLE MEMBER_TB(
    MEMBER_ID 			VARCHAR(20) PRIMARY KEY,
    MEMBER_PW 			VARCHAR(1000),
	MEMBER_NAME 		VARCHAR(50),
	MEMBER_GENDER 		VARCHAR(10),
	MEMBER_BIRTH_Y 		VARCHAR(20),
	MEMBER_BIRTH_M 		VARCHAR(20),
	MEMBER_BIRTH_D 		VARCHAR(20),
	HP1 				VARCHAR(20),
	HP2 				VARCHAR(20),
	HP3 				VARCHAR(20),
	SMSSTS_YN 			VARCHAR(20),
	EMAIL 				VARCHAR(20),
	EMAILSTS_YN 		VARCHAR(20),
	ZIPCODE 			VARCHAR(20),
	ROADADDRESS 		VARCHAR(500),
	JIBUNADDRESS 		VARCHAR(500),
	NAMUJIADDRESS 		VARCHAR(500),
    MEMBERSHIP_POINT	INT(11),
	JOIN_DATE 			DATE
);


CREATE TABLE PRODUCTS_TB(
    PRODUCTS_ID 			VARCHAR(100) PRIMARY KEY,
    PRODUCTS_NAME 			VARCHAR(50),
    PRODUCTS_BRAND			VARCHAR(50),
    PRODUCTS_STATUS			VARCHAR(50),
    ORIGINAL_PRICE			INT(11),
    SALE_PRICE				INT(11),
    PUBLISHED_DATE			DATE,
    DELIVERY_PRICE			INT(11),
    PRODUCTS_SORT			VARCHAR(50),
	DELIVERY_METHOD			VARCHAR(50),
    DELIVERY_DATE			DATE,
    BRAND_INTRO				VARCHAR(2000),
    PRODUCTS_INTRO			VARCHAR(2000),
    PRODUCTS_SIZE			VARCHAR(2000),
    PRODUCTS_POINT			INT(11),
    PRODUCTS_IMAGE			VARCHAR(2000),
    PRODUCTS_COLOR			VARCHAR(2000)
);


CREATE TABLE ORDER_TB(
	ORDER_ID 			INT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_ID 			VARCHAR(50),
    PRODUCTS_ID 		VARCHAR(100),
	ORIGINAL_PRICE		INT(11),
    SALE_PRICE			INT(11),
    ORDERER_NAME		VARCHAR(50),
    ORDERER_HP			VARCHAR(50),
    ORDER_PRODUCTS_QTY	INT(11),
    RECEIVER_NAME 		VARCHAR(50),
	RECEIVER_HP1		VARCHAR(20),
    RECEIVER_HP2 		VARCHAR(20),
	DELIVERY_ADDRESS 	VARCHAR(500),
	DELIVERY_METHOD 	VARCHAR(40),
	PAY_METHOD 			VARCHAR(200),
	PAY_ORDERER_HP_NUM 	VARCHAR(50), 
	PAY_ORDER_TIME 		DATE,
	CARD_COM_NAME 		VARCHAR(50),
	CARD_PAY_MONTH 		VARCHAR(20),
	DELIVERY_STATE 		VARCHAR(100),
	PRODUCTS_NAME 		VARCHAR(500),
	DELIVERY_MESSAGE 	VARCHAR(500),
	RECEIVER_HP3 		VARCHAR(20)
);